#pragma once

typedef enum MapLimit {
  MAP_WIDTH = 16,
  MAP_HEIGHT = 16,
  MAP_MAX_ENEMIES = 16
} MapLimit;

typedef enum CombatSetting {
  COMBAT_STARTING_AMMO = 48,
  COMBAT_SHOT_COOLDOWN = 8,
  COMBAT_SHOT_ANIMATION_TICKS = 5,
  COMBAT_ENEMY_STARTING_HEALTH = 2,
  COMBAT_KILL_SCORE = 100
} CombatSetting;

typedef enum RenderSetting {
  RENDER_MIN_SCREEN_WIDTH = 20,
  RENDER_MIN_SCREEN_HEIGHT = 10,
  RENDER_INPUT_TIMEOUT_MS = 16,
  RENDER_WALL_SHADE_COUNT = 16,
  RENDER_SIDE_SHADE_PENALTY = 2,
  RENDER_CEILING_PATTERN_Y_SCALE = 3,
  RENDER_CEILING_PATTERN_SPACING = 7,
  RENDER_VICTORY_FRAMES_PER_ROW = 2
} RenderSetting;

typedef enum ColorPairId {
  PAIR_FLOOR = 17,
  PAIR_HUD = 18,
  PAIR_ENEMY = 19,
  PAIR_WEAPON_TOP = 20,
  PAIR_WEAPON_FLASH = 21,
  PAIR_WEAPON_HAND = 22,
  PAIR_CEILING = 23,
  PAIR_WEAPON_SIDE = 24,
  PAIR_WEAPON_DARK = 25
} ColorPairId;

typedef enum PaletteColorId {
  PALETTE_WALL_START = 16,
  PALETTE_FLOOR = 32,
  PALETTE_WEAPON_HAND = 33
} PaletteColorId;
